### ISSUE TITLE
Question about Emoji colors

### ISSUE THREAD

**Issue by Rolograaf** [amandamcg/joplin-theme#3]
Hi Amanda,

Not sure if this is the right place to ask the question, nor if it is a Joplin bug or a CSS issue.

The emoji's in Joplin (also under version 0.7 of this theme) are multi-colored, but as soon as they are in a table they become white-on-dark. How can I get the color back in tables?

![emoji](https://user-images.githubusercontent.com/6130902/83945882-cd434300-a80d-11ea-9e95-afe8dc4fdfc3.gif)

**Comment by amandamcg** [comment]
@Rolograaf 
Hmm, that isn't happening for me. 

![table emoji](https://user-images.githubusercontent.com/8716226/83980309-8581f180-a8c9-11ea-918f-bb3778f26969.png)
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is   ✅   | right-aligned | $16
| col 2 is      | centered      |   $1 |
| zebra stripes | are neat  👶    |    $1 |
```

Can you post a code snippet?

**Comment by amandamcg** [comment]
Also, looking at the emoji, I am wondering if you are on a different OS than me. I am testing from a Mac.

**Comment by Rolograaf** [comment]
Mmm, yes I am on Win10.  I am trying this at work and there it seems to work in full color. Strange...

![test_theme_emoji_in_table](https://user-images.githubusercontent.com/6130902/84003014-aac63c80-a969-11ea-9952-84a12ae3a442.jpg)

Will do some more research back home, sorry about the issue.

Lourens

**Comment by Rolograaf** [comment]
I am now on Joplin 1.0.218 (prod, win32) and theme 0.7.1
The issue with white-on-dark emoji seemed to be solved at homecomputer, but when I clicked the `code-view` button, the emoji's in the table where de-colorized again. Strange thing when I `Ctrl-G` goto that note with the table, in a quick flash I see colored emoji's but immediately screen is overwritten as the first image in this issue conversation. The external editor does not show the issue.
![test2](https://user-images.githubusercontent.com/6130902/84188722-59ff3280-aa94-11ea-902e-38f820c0745d.png)

Also I had strange colors in the MD-source Layout mode, light gras green and faded orange. I restarted Joplin once more and now it is back to white and light blue characters.

Anyway I will close this issue, since it has nothing to do with your nice theme

**Comment by amandamcg** [comment]
Ah interesting, yea I havent been using the WYSIWYG editor, so maybe it has something to do with that? Anyways, hope you get it resolved!

**Comment by Rolograaf** [comment]
Yes, I had to test 
- New: Add option to choose Code Mirror as code editor ([#3284](https://github.com/laurent22/joplin/pull/3284) by @CalebJohn)

But nothing to see... And still in Beta try-out stage.

You are the same as me, do not need the WYSIWIG editing, 
(I am oldskool from the F5-under-water screen in Wordperfect 5.1 period)
