### ISSUE TITLE
TOC not functionnal when exporting in .pdf or when printing

### ISSUE THREAD

**Issue by Klemet** [amandamcg/joplin-theme#6]
Hello there !

Thank you for your theme, it's quite gorgeous ! But as I wanted to use it and to tweak it, I realized that the awesome display of the Table Of Content that you created also came when printing or exporting the note in .pdf format, which did not result in something functional (as the box cannot be scolled down in .pdf format or when printed, obviously).

Now, maybe this is because I already tweaked the .css code when I noticed it, and maybe you already took care of the issue; I'm sorry for the disturbance if that's the case. But if not, I propose the solution of putting the lines concerning the formatting of the table of content into a "@media screen" tag, like this :

```
@media screen {

	nav.table-of-contents>ul {
    	top: 0;
 	   right: 0;
  	  position: fixed;
  	  z-index: var(--z-toc);
  	  background: var(--dark-grey);
 	   padding: var(--base-size-8);
   	 border-radius: var(--base-size-4);
   	 max-width: 15%;
   	 font-size: calc(var(--font-size)/1.3) !important;
  	  max-height: var(--base-size-272);
   	 overflow: scroll;
   	 opacity: 0.8;
	}

	nav.table-of-contents ul {
 	   list-style-type: none;
 	   margin-left: var(--base-size-4);
	}

	nav.table-of-contents li {
  	  white-space: nowrap;
   	 overflow: hidden;
   	 text-overflow: ellipsis;
   	 margin-bottom: 0;
	}

	nav.table-of-contents li a {
    	padding: 0;
  	  color: var(--light-grey) !important;
	}

	@media all and (min-width: 920px) {
   	 nav.table-of-contents>ul {
   	     height: 100%;
   	     max-height: 100%;
   	 }

   	 #rendered-md {
   	     width: 75%;
   	 }
	}

}
```

Using this, this resulted into your awesome TOC display while watching the note in Joplin, and in a normal-looking TOC when exporting in .pdf or printing.

Hope it'll be of some help !

**Comment by amandamcg** [comment]
Good call @Klemet, I have updated this! Thanks for reporting
